fixtures:
  repositories:
    "puppi":
      repo: "git://github.com/Adaptavist/puppi.git"
    "monitor":
      repo: "git://github.com/Adaptavist/puppet-monitor.git"
    "iptables":
      repo: "git://github.com/Adaptavist/puppet-iptables.git"
    "stdlib":
      repo: "git://github.com/Adaptavist/puppetlabs-stdlib.git"
    "concat":
      repo: "git://github.com/Adaptavist/puppetlabs-concat.git"
  symlinks:
    "fail2ban": "#{source_dir}"

